#!/usr/bin/env bash
# display information about the subdomains
# use dig to display info and awk

disp() {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  disp "$1" "www"
  disp "$1" "lb-01"
  disp "$1" "web-01"
  disp "$1" "web-02"
elif [ "$#" == 2 ]
then
  disp "$1" "$2"
fi
