#!/usr/bin/env bash
# install nginx

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html

# webpage - 404error
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

# redirect for 404 error page
string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default

service nginx start
