#!/usr/bin/env bash
# install haproxy

apt-get update
apt-get -y install haproxy

# configure server files

server_config=\
"
frontend http
  bind *:80
  mode http
  default_backend web-backend
  
backend web-backend
   balance roundrobin
   server 129089-web-01 54.237.56.180:80 check
   server 129089-web-02 52.91.165.205:80 check
   
"

echo "$server_config" >> /etc/haproxy/haproxy.cfg

service haproxy restart
