#!/usr/bin/env bash
# why ngnx container isnt installing

apt-get update
apt-get -y install nginx
# using sed "s" - substitute port 8080 with 80
# g -global   
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
