#!/usr/bin/env bash
# why ngnx container isnt installing

apt-get update
apt-get -y install nginx
# s - creates symbolic link
# f - deletes file and replace
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
