#!/usr/bin/env bash
# daemons programs

FILE=/var/run/my_process.pid

start() {
	sudo ./manage_my_process &
  	echo $$ > $FILE
}

stop(){
	sudo pkill  -f "./manage_my_process" && [ -e "$FILE" ] && rm -f "$FILE"
}

if [ "$1" == "start" ]
then
	start
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
	stop
	 echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
	stop
	start
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
	
	

